import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import Nav from './components/Nav'
import Footer from './components/Footer'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'NourifyRuoka',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <div className="flex flex-col h-screen">
          <Nav />
          <div className="container mx-auto flex-grow">
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
